apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulut-bilisim-odevi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulut-bilisim-odev
  template:
    metadata:
      labels:
        app: bulut-bilisim-odev
    spec:
      containers:
      - name: bulut-bilisim-odevi-kub
        image: rasit289/bulut_bilisim_container:v7
        ports:
        - containerPort: 8080