apiVersion: v1
kind: Service
metadata:
  name: bulut-bilisim-odevi-servis
spec:
  selector:
    name: bulut-bilisim-odevi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer