apiVersion: v1
kind: Service
metadata:
  name: bulut_bilisim_odevi_servis
spec:
  selector:
    name: bulut_bilisim_odevi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
